### ISSUE TITLE
调用ActivityResult 的拍照API报错

### ISSUE THREAD

**Issue by Linnnnnn** [DylanCaiCoding/Longan#19]
kotlin.UninitializedPropertyAccessException: lateinit property fileProviderAuthority has not been initialized
        at com.dylanc.longan.UriKt.getFileProviderAuthority(Uri.kt:42)
        at com.dylanc.longan.UriKt.toUri$default(Uri.kt:57)
        at com.dylanc.longan.activityresult.SaveToUriLauncher.launchAndSaveToCache(ActivityResultLauncher.kt:68)
       

已经配置FILE_PROVIDER

**Comment by Linnnnnn** [comment]
已解决

**Comment by DylanCaiCoding** [comment]
我在文档补充一下要设置 fileProviderAuthority

**Comment by Diper1996** [comment]
@Linnnnnn 如何解决的？

**Comment by Linnnnnn** [comment]
> 

在Application中设置fileProviderAuthority

**Comment by Linnnnnn** [comment]
> @Linnnnnn 如何解决的？

在Application中设置fileProviderAuthority
